# EasyJetpack configuration file
# Version 1.8.0 Release

jetpacks:
    # Traditional, or 'puff' Jetpack
    traditional:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: GOLD_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    burst:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: GOLD_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    teleport:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: CHAINMAIL_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    rocket:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: CHAINMAIL_CHESTPLATE
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    boots:
        # Are these fallboots enabled?
        enabled: true
        # The name of the Material used.
        material: LEATHER_BOOTS
        # Is durability enabled on these boots?
        durability: true
        # Are the boots craftable?
        craftable: true
        # Do the boots need a Jetpack to function?
        jetpackrequired: false
        # Is the Jetpack repairable?
        antianvil: true
fuel:
    # Is fuel usage enabled?
    enabled: true
    # The name of the Material used.
    material: COAL
    # Durability of the Material (-1 for any), for example:
    # to match coal and charcoal, use -1. To match coal only, 0, and
    # charcoal, 1.
    durability: -1
