name: InfinityJetpacks
main: main.java.me.paulvogel.easyjetpack.EasyJetpack
version: 1.8.1 Release
authors: [j_selby, Paul Vogel, DarknesGaming]
softdepend: [NoCheatPlus]
permissions:
   easyjetpack.jetpackname:
      description: Allows a player to use a jetpack
      default: op
   easyjetpack.admin:
      description: Allows access to /ej
      default: op
   easyjetpack.nofall:
      description: Disables all fall damage, while wearing a jetpack
      default: op
commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      
