name: InfinityJetpacks
main: me.paulvogel.easyjetpack.EasyJetpack
version: 1.7.0 Release
authors: [j_selby, Paul Vogel, DarknesGaming]
softdepend: [AntiCheatReloaded, NoCheatPlus]
permissions:
   easyjetpack.jetpackname:
      description: Allows a player to use a jetpack
      default: op
   easyjetpack.admin:
      description: Allows access to /ej
      default: op
   easyjetpack.nofall:
      description: Disables all fall damage, while wearing a jetpack
      default: op
   easyjetpack.infinity:
      description: Operation of the Infinity Jetpack
      default: true
   easyjetpack.secretitem1:
      description: Secret Diamond Block recipe from Infinity Laboratories
      default: true
   easyjetpack.lavabucket:
      description: Craftable Lava Bucket from Infinity Laboratories
      default: true
   easyjetpack.secretitem2:
      description: Secret Emerald recipe from Infinity Laboratories
      default: true
   easyjetpack.secretitem3:
      description: Secret Nether Star recipe from Infinity Laboratories
      default: true
   easyjetpack.elytra:
      description: The Elytra recipe from Infinity Laboratories.
      default: true
commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      
