name: EasyJetpack
main: com.github.jselby.ej.EasyJetpack
version: 0.7
permissions:
   easyjetpack.jetpackname:
      description: Allows a player to use a jetpack
      default: op
commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      
