name: EasyJetpack
main: net.jselby.ej.EasyJetpack
version: 1.2
author: j_selby
softdepend: [AntiCheat]
permissions:
   easyjetpack.jetpackname:
      description: Allows a player to use a jetpack
      default: op
   easyjetpack.admin:
      description: Allows access to /ej
      default: op
   easyjetpack.nofall:
      description: Disables all fall damage, while wearing a jetpack
      default: op
commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      
